spring.application.name=customer
spring.datasource.url=jdbc:postgresql://localhost:5432/customer_db
spring.datasource.username=josiah
spring.datasource.password=Holycraft@30
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false